/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
/**
 *
 * @author bayujp
 */
public class balikbuku extends javax.swing.JFrame {
String kembali;
String pulang;
    /**
     * Creates new form balikbuku
     */
    public balikbuku()  {
        initComponents();
        tampil();
        kosong();
         
       
  
        try {
             BufferedImage beam = ImageIO.read(getClass().getResource("library.jpg"));
             setIconImage(beam); 
        } catch (IOException ex) {
            Logger.getLogger(splashscreen.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.setTitle("Form Pengembalian Buku");
    }
private void kosong(){
    txttelat.setEditable(true);
    txtdenda.setEditable(true);
    txtbayar.setEditable(true);
    txtkembalian.setEditable(true);
    tglkembali.setDate(null);
    tglkembali.setEnabled(false);  
    
    txtid.setText("ID Peminjaman");
    txtpinjam.setText("Tanggal Peminjaman");
    txtblk.setText("Tanggal Balik");
    txttelat.setText("Keterlambatan");
    txtdenda.setText("Denda");
    txtbayar.setText("Bayar");
    txtkembalian.setText("Kembali"); 
    txtkembalian.setEditable(false);
       txtid.setEditable(false);
       txtpinjam.setEditable(false);
       txtblk.setEditable(false);
       txttelat.setEditable(false);
       txtdenda.setEditable(false);
    tglkembali.setEnabled(false);
    jButton3.setEnabled(false);
  jButton1.setEnabled(false);
  jButton4.setEnabled(false);
  
       
}    
private void tampil(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Npm");
        model.addColumn("Nama");
        model.addColumn("Id_buku");
        model.addColumn("judul");
        model.addColumn("Jumlah");
        model.addColumn("Tgl Pinjam");
        model.addColumn("Tgl Kembali");
        model.addColumn("Denda");
        model.addColumn("Status");
        try{
            String status = "Belum Kembali";
            String query = "select*from pinjaman where status = '"+status+"'";
            java.sql.Connection kon = (Connection) koneksi.koneksi();
            java.sql.Statement stm = kon.createStatement();
            java.sql.ResultSet data = stm.executeQuery(query);
            
            while(data.next()){
                model.addRow(new Object [] {data.getString(1),data.getString(2),
                data.getString(3),data.getString(4),data.getString(5),data.getString(6),
                data.getString(7),data.getString(8),data.getString(9),data.getString(10)});
            }
            tblpinjam.setModel(model);
        }
        catch(Exception b){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpinjam = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        txtpinjam = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        tglkembali = new com.toedter.calendar.JDateChooser();
        txtkembalian = new javax.swing.JTextField();
        txtblk = new javax.swing.JTextField();
        txttelat = new javax.swing.JTextField();
        txtdenda = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtsrc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblpinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpinjam);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 790, 243));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, -1));
        jPanel1.add(txtpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 219, 33));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 219, 33));

        tglkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglkembaliPropertyChange(evt);
            }
        });
        tglkembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tglkembaliKeyPressed(evt);
            }
        });
        jPanel1.add(tglkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 110, -1));

        txtkembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtkembalianMouseClicked(evt);
            }
        });
        jPanel1.add(txtkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 219, 33));
        jPanel1.add(txtblk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 219, 33));
        jPanel1.add(txttelat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 219, 33));

        txtdenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdendaActionPerformed(evt);
            }
        });
        jPanel1.add(txtdenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 219, 33));

        txtbayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbayarMouseClicked(evt);
            }
        });
        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbayarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbayarKeyTyped(evt);
            }
        });
        jPanel1.add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 219, 33));

        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 100, -1));

        jButton3.setText("Hitung");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 100, -1));

        jButton4.setText("Proses");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 100, -1));

        txtsrc.setText("Search NPM");
        txtsrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsrcMouseClicked(evt);
            }
        });
        txtsrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsrcActionPerformed(evt);
            }
        });
        txtsrc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsrcKeyReleased(evt);
            }
        });
        jPanel1.add(txtsrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 110, 30));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("PENGEMBALIAN BUKU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new beranda().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblpinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpinjamMouseClicked
jButton1.setEnabled(true);   
tglkembali.setEnabled(true);
txtbayar.setEditable(true);
        try{
        
     int baris = tblpinjam.getSelectedRow();
        String id= tblpinjam.getValueAt(baris, 0).toString();
        
            String query = "select*from pinjaman where id_pinjam = '"+id+"'";
            java.sql.Connection kon = (Connection) koneksi.koneksi();
            java.sql.Statement stm = kon.createStatement();
            java.sql.ResultSet data = stm.executeQuery(query);
            
            while(data.next()){
        
                txtid.setText(data.getString(1));
            txtpinjam.setText(data.getString(7));
            txtblk.setText(data.getString(8));
            kembali = data.getString(8);
            }
            
    }
        catch(Exception b){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblpinjamMouseClicked

    private void tglkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglkembaliPropertyChange
if (tglkembali.getDate() != null) {
     SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd MMMM yyyy");
     pulang = FormatTanggal.format(tglkembali.getDate());
}
try {
    DateFormat format = new SimpleDateFormat("dd MMMM yyyy");
    Date tanggalpinjam = format.parse(kembali);
    Date tanggalkembali = format.parse(pulang);
    long tanggalpinjam1 = tanggalpinjam.getTime();
    long tanggalkembali1 = tanggalkembali.getTime();
    long diff = tanggalkembali1 - tanggalpinjam1;
    long lama = diff / (24 * 60 * 60 * 1000);
    txttelat.setText(Long.toString(lama) + "");

int denda;
int telat = Integer.parseInt(txttelat.getText());
denda = telat*5000;
String tlt;
 tlt = String.valueOf(denda);   
if(telat<0){
txttelat.setText("Keterlambatan");
txtdenda.setText("Denda");
txtbayar.setText("Bayar");
txtkembalian.setText("Kembali");
jButton3.setEnabled(false);  
jButton4.setEnabled(false);
jButton1.setEnabled(true);
}
else if(tlt.equals("0")){
txtbayar.setText("0");
 txtdenda.setText("0");
txtkembalian.setText("0");
txtbayar.setEditable(false);
jButton3.setEnabled(false);
jButton4.setEnabled(true);
jButton1.setEnabled(true);
}
else{
txtbayar.setEditable(true);
txtbayar.setText("Bayar");
txtkembalian.setText("Kembali");
jButton3.setEnabled(true); 
jButton4.setEnabled(true);
jButton1.setEnabled(true);
txtdenda.setText(tlt);
}
} catch (Exception e) {
    System.out.println("" + e.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_tglkembaliPropertyChange

    private void txtbayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbayarMouseClicked
txtbayar.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarMouseClicked

    private void txtkembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkembalianMouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int bayar = Integer.parseInt(txtbayar.getText());
int denda = Integer.parseInt(txtdenda.getText());

if(bayar<denda){
   JOptionPane.showMessageDialog(null,"Tidak Boleh Kurang!"); 
}
else{
  int total = bayar-denda;
String ttl;
ttl = String.valueOf(total);
txtkembalian.setText(ttl);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tglkembaliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglkembaliKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglkembaliKeyPressed

    private void txtsrcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsrcMouseClicked
        txtsrc.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrcMouseClicked

    private void txtsrcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsrcKeyReleased
if(txtsrc.getText().equals("")){
 tampil();   
}
else{
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Npm");
        model.addColumn("Nama");
        model.addColumn("Id_buku");
        model.addColumn("judul");
        model.addColumn("Jumlah");
        model.addColumn("Tgl Pinjam");
        model.addColumn("Tgl Kembali");
        model.addColumn("Denda");
        model.addColumn("Status");
        try{
            String status="Belum Kembali";
            String query = "select * from pinjaman where npm = '"+txtsrc.getText()+"'"
                    + "&& status = '"+status+"'";
            java.sql.Connection kon = (Connection) koneksi.koneksi();
            java.sql.Statement stm = kon.createStatement();
            java.sql.ResultSet data = stm.executeQuery(query);

            while(data.next()){
                model.addRow(new Object [] {data.getString(1),data.getString(2),
                    data.getString(3),data.getString(4),data.getString(5),data.getString(6),
                    data.getString(7),data.getString(8),data.getString(9),data.getString(10)});
        }
        tblpinjam.setModel(model);
        }
        catch(Exception b){

        }    
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtsrcKeyReleased

    private void txtsrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrcActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    try {
        String status = "Sudah Kembali";
            String sql ="UPDATE pinjaman SET denda = '"+txtdenda.getText()
                    +"',status = '"+status
                    +"' WHERE id_pinjam = '"+txtid.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.koneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
 try{
        
        String id= txtid.getText();
        
            String query = "select id_buku from pinjaman where id_pinjam = '"+id+"'";
            java.sql.Connection kon = (Connection) koneksi.koneksi();
            java.sql.Statement stm = kon.createStatement();
            java.sql.ResultSet data = stm.executeQuery(query);
            
            while(data.next()){
        String aidi = data.getString("id_buku");
        try{
  String query1 = "select*from buku where id_buku = '"+aidi+"'";
 java.sql.Connection kon1 = (Connection) koneksi.koneksi();
 java.sql.Statement st = kon1.createStatement();
 java.sql.ResultSet data1 = st.executeQuery(query1);
 
 while(data1.next()){
      int baris = tblpinjam.getSelectedRow();
        String jmlh= tblpinjam.getValueAt(baris, 5).toString();
     int jumlah= Integer.parseInt(data1.getString(7));
     int jumlahpinjam = Integer.parseInt(jmlh);
     int total = jumlah+jumlahpinjam;
    try {
            String sql1 ="UPDATE buku SET stok = '"+total
                    +"' WHERE id_buku = '"+aidi+"'";
            java.sql.Connection conn1=(Connection)koneksi.koneksi();
            java.sql.PreparedStatement pst=conn1.prepareStatement(sql1);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
     
 }
}
catch(Exception b){
 JOptionPane.showMessageDialog(null, b.getMessage());
}
            }
            
    }
        catch(Exception b){
            
        }
 tampil();
 kosong();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtdendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdendaActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtbayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarKeyPressed

    private void txtbayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyTyped
char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) ||
                (c == KeyEvent.VK_BACK_SPACE) ||
                (c == KeyEvent.VK_DELETE))
                )
            )
        {
            evt.consume();
        }            // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
kosong();
txtkembalian.setEditable(false);
       txtid.setEditable(false);
       txtpinjam.setEditable(false);
       txtblk.setEditable(false);
       txttelat.setEditable(false);
       txtdenda.setEditable(false);
    tglkembali.setEnabled(false);
    jButton3.setEnabled(false);
  jButton1.setEnabled(false);
  jButton4.setEnabled(false);
  txtbayar.setEditable(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpinjam;
    private com.toedter.calendar.JDateChooser tglkembali;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtblk;
    private javax.swing.JTextField txtdenda;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtpinjam;
    private javax.swing.JTextField txtsrc;
    private javax.swing.JTextField txttelat;
    // End of variables declaration//GEN-END:variables
}
